backend:
    name: github
    repo: fmajorcminor/portfolio # e.g. dallin-christensen/portfolio
    branch: main
    # Cloudflare Pages handles the OAuth callback
    base_url: https://dallin-christensen.com # your Cloudflare Pages URL
    auth_endpoint: api/auth

media_folder: public/images/blog
public_folder: /images/blog

collections:
    - name: posts
      label: Blog Posts
      folder: src/posts
      create: true
      slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
      fields:
          - { label: Title, name: title, widget: string }
          - { label: Date, name: date, widget: datetime }
          - {
                label: Description,
                name: description,
                widget: string,
                required: false,
            }
          - { label: Tags, name: tags, widget: list, required: false }
          - { label: Draft, name: draft, widget: boolean, default: false }
          - { label: Body, name: body, widget: markdown }
